brew "bat"
brew "btop"
brew "container"
brew "fd"
brew "git-delta"
brew "go@1.25", link: true
brew "htop"
brew "neovim"
brew "node"
brew "pnpm@10", link: true
brew "python@3.12"
brew "ripgrep"
brew "rustup"
brew "tree"
brew "uv"
brew "zoxide"
cask "android-platform-tools"
cask "codex"
