brew "btop"
brew "container"
brew "fd"
brew "git-delta"
brew "go@1.25", link: true
brew "htop"
brew "neovim"
brew "node"
brew "pnpm"
brew "python@3.12"
brew "ripgrep"
brew "uv"
brew "zoxide"
cask "android-platform-tools"
