#!/bin/sh

# zsh
ln -f zprofile ~/.zprofile

# ghostty
mkdir -p ~/.config/ghostty
ln -f ghostty.conf ~/.config/ghostty/config

# nvim
mkdir -p ~/.config/nvim
ln -f nvim.vim ~/.config/nvim/init.vim

# zed
mkdir -p ~/.config/zed
ln -f zed/settings.json ~/.config/zed/settings.json
ln -f zed/keymap.json ~/.config/zed/keymap.json
